// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/besta-home/AIStylistChat.tsx": () => import("../components/mockups/besta-home/AIStylistChat.tsx"),
  "./components/mockups/besta-home/EditorialLookbook.tsx": () => import("../components/mockups/besta-home/EditorialLookbook.tsx"),
  "./components/mockups/besta-home/ForYouReel.tsx": () => import("../components/mockups/besta-home/ForYouReel.tsx"),
  "./components/mockups/besta-home/LiveDropFeed.tsx": () => import("../components/mockups/besta-home/LiveDropFeed.tsx")
};
